### ISSUE TITLE
Specifically Which source to use

### ISSUE THREAD

**Issue by timseed** [JonathanRaiman/wikipedia_ner#1]
Before I pull down 25Gb of data - which data source are you using for this.

I read that it uses **enwiki.bz2**, but  [https://dumps.wikimedia.org/enwiki/](https://dumps.wikimedia.org/enwiki/) has so many types of dumps - I am unsure as to which one to use.

**Comment by JonathanRaiman** [comment]
The`pages-articles` version ([`enwiki-latest-pages-articles.xml.bz2`](https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2))

**Comment by timseed** [comment]
Many thanks - got it.
